import "./reset.css";
import "./globals.css";
import type { Metadata } from "next";
import { montserrat, libre } from "@/lib/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${libre.variable}`}>
        {children}
      </body>
    </html>
  );
}
