import "./reset.css";
import "./globals.css";
import type { Metadata } from "next";
import { montserrat, libre } from "@/lib/font";
import { Footer, Navbar } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${libre.variable}`}>
        <Navbar />
        <main style={{ paddingTop: "7rem" }}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
